name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install pandas numpy scikit-learn mlflow joblib matplotlib seaborn

      - name: Run Training Script
        shell: bash -l {0}
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          cd MLProject
          python modelling.py

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/